FROM node:20.15.1

WORKDIR /frontend

COPY package*.json ./

RUN npm install

COPY . .

COPY .env.local ./

# ARG API_URL
# ENV API_URL=$BUILD_API_URL

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]