ARG PYTHON_VERSION=3.10.12
FROM python:${PYTHON_VERSION} as base

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app
# COPY ./.env /code/.env

# ENV PYTHONPATH=${PYTHONPATH}:/code/app

# RUN python /code/app/initial_data.py

EXPOSE 8000

CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"]