ARG PYTHON_VERSION=3.10.12
FROM python:${PYTHON_VERSION} as base

WORKDIR /code

COPY ./requirements_initialdata.txt /code/requirements_initialdata.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements_initialdata.txt

COPY ./app /code/app

ENV PYTHONPATH=/code

CMD ["python", "app/initial_data.py"]